src/apps/testing/urls.py
from django.urls import path

from .constants import APP_NAME
from .views.task_views import TaskDeleteView
from .views.task_views.closed_question_views import ClosedQuestionCreateView, ClosedQuestionUpdateView, \
    ClosedQuestionDetailView
from .views.task_views.open_question_views import OpenQuestionCreateView, OpenQuestionUpdateView, OpenQuestionDetailView
from .views.task_views.sequencing_views import SequencingCreateView, SequencingUpdateView
from .views.task_views.sequencing_views.sequencing_detail_view import SequencingDetailView
from .views.testing_views import TestingCreateView, TestingUpdateView, TestingDeleteView, TeacherTestingDetailView, \
    StudentSolvingTestingDetailView
from .views.testing_views.testing_detail_view import redirect_testing_detail_view

app_name = APP_NAME
urlpatterns = [
    path('journal/<journal_pk>/create', TestingCreateView.as_view(), name='testing_create'),
    path('<pk>/redirect_detail', redirect_testing_detail_view, name='testing_detail'),
    path('<pk>/detail', TeacherTestingDetailView.as_view(), name='teacher_testing_detail'),
    path('<pk>/solving_task_list', StudentSolvingTestingDetailView.as_view(), name='student_testing_detail'),

    path('update/<pk>', TestingUpdateView.as_view(), name='testing_update'),
    path('delete/<pk>', TestingDeleteView.as_view(), name='testing_delete'),

    path('<testing_pk>/task/closed_question/<type>/create', ClosedQuestionCreateView.as_view(),
         name='task_closed_question_create'),
    path('task/closed_question/detail/<pk>', ClosedQuestionDetailView.as_view(),
         name='task_closed_question_detail'),
    path('task/closed_question/update/<pk>', ClosedQuestionUpdateView.as_view(),
         name='task_closed_question_update'),

    path('<testing_pk>/task/open_question/<type>/create', OpenQuestionCreateView.as_view(),
         name='task_open_question_create'),
    path('task/open_question/detail/<pk>', OpenQuestionDetailView.as_view(),
         name='task_open_question_detail'),
    path('task/open_question/update/<pk>', OpenQuestionUpdateView.as_view(),
         name='task_open_question_update'),

    path('<testing_pk>/task/sequencing/<type>/create', SequencingCreateView.as_view(),
         name='task_sequencing_create'),
    path('task/sequencing/detail/<pk>', SequencingDetailView.as_view(),
         name='task_sequencing_detail'),
    path('task/sequencing/update/<pk>', SequencingUpdateView.as_view(),
         name='task_sequencing_update'),

    path('task/delete/<pk>', TaskDeleteView.as_view(), name='task_delete'),
]

src/apps/testing_by_code/urls.py
from django.urls import path

from .views.solving_testing_views import StudentSolvingTestingDetailView
from .views.task_views import TaskDetailView, update_task, duplicate_task, delete_task, add_task_form, \
    update_tasks_serial_number_view
from .views.testing_views import TestingCreateView, TestingUpdateView, \
    TestingDeleteView, TeacherTestingDetailView
from .views.testing_views.testing_detail_view import redirect_testing_detail_view

app_name = 'testing_by_code'
urlpatterns = [
    path('journal/<journal_pk>/create/', TestingCreateView.as_view(), name='testing_create'),
    path('<pk>/redirect_detail/', redirect_testing_detail_view, name='testing_detail'),
    path('<pk>/detail/', TeacherTestingDetailView.as_view(), name='teacher_testing_detail'),
    path('<pk>/solving_task_list/', StudentSolvingTestingDetailView.as_view(), name='student_testing_detail'),

    path('<pk>/update/', TestingUpdateView.as_view(), name='testing_update'),
    path('<pk>/delete/', TestingDeleteView.as_view(), name='testing_delete'),
    path('task/<pk>/detail/', TaskDetailView.as_view(), name='task_detail'),
    path('task/<pk>/update/', update_task, name='update_task'),
    path('task/<pk>/duplicate/', duplicate_task, name='duplicate_task'),
    path('task/<pk>/delete/', delete_task, name='delete_task'),
    path('add_task_form/', add_task_form, name='add_task_form'),
    path('<pk>/update_tasks_serial_number/', update_tasks_serial_number_view, name='update_tasks_serial_number'),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('', include('apps.user.urls', namespace='user')),
    path('testing/', include('apps.testing.urls', namespace='testing')),
    path('testing_by_code/', include('apps.testing_by_code.urls', namespace='testing_by_code')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('pwa.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    from django.urls import re_path
    from django.views.static import serve

    urlpatterns += [re_path(r'media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}), ]

src/apps/testing/models/max_score.py
from typing import Iterable

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from apps.testing.constants import APP_NAME


class MaxScore(models.Model):
    five = models.IntegerField(
        default=100,
        validators=[
            MaxValueValidator(100),
            MinValueValidator(1)
        ],
        verbose_name='Отлично'
    )
    four = models.IntegerField(
        default=80,
        validators=[
            MaxValueValidator(100),
            MinValueValidator(1)
        ],
        verbose_name='Хорошо'
    )
    three = models.IntegerField(
        default=60,
        validators=[
            MaxValueValidator(100),
            MinValueValidator(1)
        ],
        verbose_name='Удовлетворительно'
    )
    two = models.IntegerField(
        default=40,
        validators=[
            MaxValueValidator(100),
            MinValueValidator(1)
        ],
        verbose_name='Неудовлетворительно'
    )

    def get_fields(self) -> Iterable:
        from apps.testing.services import get_model_fields
        return get_model_fields(
            model=self,
            excluded_fields=['id']
        )

    class Meta:
        db_table = f'{APP_NAME}_max-score'

src/apps/testing/models/solving_testing.py
from abstractions.abstract_models import AbstractSolvingTesting
from apps.testing.constants import APP_NAME


class SolvingTesting(AbstractSolvingTesting):
    class Meta(AbstractSolvingTesting.Meta):
        db_table = f'{APP_NAME}_solving-testing'

src/apps/testing_by_code/models/cycle.py
from django.db import models
from django.urls import reverse

from config.settings import MAX_LENGTH


class Cycle(models.Model):
    title = models.CharField(max_length=MAX_LENGTH, verbose_name='Цикл')

    def get_absolute_url(self):
        return reverse('cycle_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Цикл'
        verbose_name_plural = 'Циклы'

src/apps/testing/forms/max_score_form.py
from django import forms

from apps.testing.constants import MIN_ASSESSMENT_THRESHOLD, MAX_ASSESSMENT_THRESHOLD
from apps.testing.models import MaxScore


class MaxScoreForm(forms.ModelForm):
    class Meta:
        model = MaxScore
        number_input = forms.NumberInput(attrs={
            'class': 'uk-margin-small uk-input uk-width-small',
            'min': MIN_ASSESSMENT_THRESHOLD,
            'max': MAX_ASSESSMENT_THRESHOLD
        })
        widgets = {
            'five': number_input,
            'four': number_input,
            'three': number_input,
            'two': number_input
        }
        fields = '__all__'

src/apps/testing/forms/testing_form.py
from django import forms

from abstractions.abstract_forms import AbstractTestingForm
from apps.base_testing.constants import MIN_ASSESSMENT_THRESHOLD, MAX_ASSESSMENT_THRESHOLD
from apps.testing.constants import MAX_PROBABILITY_OF_GUESSING
from apps.testing.models import Testing


class TestingForm(AbstractTestingForm):
    class Meta(AbstractTestingForm.Meta):
        CLASS = 'uk-margin-small uk-input uk-width-small'
        model = Testing
        widgets = AbstractTestingForm.Meta.widgets | {
            'number': forms.NumberInput(attrs={
                'class': CLASS,
            }),
            'probability_of_guessing': forms.NumberInput(attrs={
                'class': CLASS,
                'max': MAX_PROBABILITY_OF_GUESSING,
                'min': 0,
                'step': '0.01'
            }),
            'assessment_threshold': forms.NumberInput(attrs={
                'class': CLASS,
                'min': MIN_ASSESSMENT_THRESHOLD,
                'max': MAX_ASSESSMENT_THRESHOLD,
            }),
        }
        exclude = ('date_of_deletion', 'max_score', 'journal')

src/apps/testing_by_code/forms.py
from django import forms

from abstractions.abstract_forms import AbstractTestingForm, AbstractTaskForm
from apps.testing_by_code.models.setting import Setting
from apps.testing_by_code.models.cycle import Cycle
from apps.testing_by_code.models.operator_nesting import OperatorNesting
from apps.testing_by_code.models.testing import Testing
from apps.testing_by_code.models.task import Task
from apps.testing_by_code.types import OperatorPresenceType, ConditionType

CLASS_UK_SELECT = 'uk-select'
CLASS_UK_FORM_WIDTH_SMALL = 'uk-form-width-small'
SELECT_TAG_CLASSES = f'{CLASS_UK_SELECT} {CLASS_UK_FORM_WIDTH_SMALL}'


class TestingForm(AbstractTestingForm):
    class Meta:
        model = Testing
        fields = (
            'title',
            'student_groups',
            'is_published',
            'is_review_of_result_by_student'
        )


class TaskForm(AbstractTaskForm):
    class Meta:
        model = Task
        fields = ('weight',)


class SettingForm(forms.ModelForm):
    BE_PRESENT = 'Присутствует'
    ABSENT = 'Отсутствует'
    choices_is_operator = (
        (BE_PRESENT, BE_PRESENT),
        (ABSENT, ABSENT)
    )
    is_if_operator = forms.ChoiceField(
        label='Наличие оператора if',
        widget=forms.Select(
            attrs={
                'class': SELECT_TAG_CLASSES
            }
        ),
        choices=choices_is_operator
    )

    SIMPLE = 'Простое'
    COMPOSITE = 'Составное'
    choices_condition_operator = (
        ('', '----'),
        (SIMPLE, SIMPLE),
        (COMPOSITE, COMPOSITE)
    )
    condition_of_if_operator = forms.ChoiceField(
        label='Условие оператора if',
        required=False,
        initial=choices_condition_operator[1],
        widget=forms.Select(
            attrs={
                'class': SELECT_TAG_CLASSES
            }
        ),
        choices=choices_condition_operator
    )
    cycle = forms.ModelMultipleChoiceField(
        label='Цикл',
        required=False,
        widget=forms.CheckboxSelectMultiple(),
        to_field_name='title',
        queryset=Cycle.objects.all()
    )
    cycle_condition = forms.ChoiceField(
        label='Условие цикла',
        required=False,
        initial=choices_condition_operator[1],
        widget=forms.Select(
            attrs={
                'class': SELECT_TAG_CLASSES
            }
        ),
        choices=choices_condition_operator
    )
    operator_nesting = forms.ModelMultipleChoiceField(
        label='Вложенность операторов',
        required=False,
        widget=forms.CheckboxSelectMultiple(),
        to_field_name='title',
        queryset=OperatorNesting.objects.all()
    )
    is_OOP = forms.CheckboxInput()
    is_strings = forms.CheckboxInput()

    def clean(self):
        cleaned_data = super().clean()
        is_if_operator = cleaned_data.get('is_if_operator')
        cycle = cleaned_data.get('cycle')
        is_OOP = cleaned_data.get('is_OOP')
        is_strings = cleaned_data.get('is_strings')

        is_absent_if_operator = is_if_operator == OperatorPresenceType.ABSENT
        if is_absent_if_operator:
            cleaned_data['condition_of_if_operator'] = ConditionType.SIMPLE
        if cycle:
            cleaned_data['cycle_condition'] = ConditionType.SIMPLE
        is_lock_nesting_of_operators = is_absent_if_operator or not cycle
        if is_lock_nesting_of_operators:
            cleaned_data['operator_nesting'] = OperatorNesting.objects.none()
        if is_OOP:
            cleaned_data = self._set_default_basic_fields(cleaned_data)
            cleaned_data['is_strings'] = False
        if is_strings:
            cleaned_data = self._set_default_basic_fields(cleaned_data)
            cleaned_data['is_OOP'] = False

    @staticmethod
    def _set_default_basic_fields(cleaned_data: dict) -> dict:
        cleaned_data['is_if_operator'] = OperatorPresenceType.ABSENT
        cleaned_data['condition_of_if_operator'] = ConditionType.SIMPLE
        cleaned_data['cycle'] = Cycle.objects.none()
        cleaned_data['cycle_condition'] = ConditionType.SIMPLE
        cleaned_data['operator_nesting'] = OperatorNesting.objects.none()
        return cleaned_data

    class Meta:
        model = Setting
        fields = '__all__'
        exclude = ['users', 'testing_by_code']

src/apps/testing_by_code/forms/setting_form.py
from django import forms

from apps.testing_by_code.models import OperatorNesting, Cycle, Setting
from apps.testing_by_code.types import ConditionType

CLASS_UK_SELECT = 'uk-select'
CLASS_UK_FORM_WIDTH_SMALL = 'uk-form-width-small'
SELECT_TAG_CLASSES = f'{CLASS_UK_SELECT} {CLASS_UK_FORM_WIDTH_SMALL}'


class SettingForm(forms.ModelForm):
    SIMPLE = 'Простое'
    COMPOSITE = 'Составное'
    choices_condition_operator = (
        ('', '----'),
        (SIMPLE, SIMPLE),
        (COMPOSITE, COMPOSITE)
    )
    condition_of_if_operator = forms.ChoiceField(
        label='Условие оператора if',
        required=False,
        initial=choices_condition_operator[1],
        widget=forms.Select(
            attrs={
                'class': SELECT_TAG_CLASSES
            }
        ),
        choices=choices_condition_operator
    )
    cycle = forms.ModelMultipleChoiceField(
        label='Цикл',
        required=False,
        widget=forms.CheckboxSelectMultiple(),
        to_field_name='title',
        queryset=Cycle.objects.all()
    )
    cycle_condition = forms.ChoiceField(
        label='Условие цикла',
        required=False,
        initial=choices_condition_operator[1],
        widget=forms.Select(
            attrs={
                'class': SELECT_TAG_CLASSES
            }
        ),
        choices=choices_condition_operator
    )
    operator_nesting = forms.ModelMultipleChoiceField(
        label='Вложенность операторов',
        required=False,
        widget=forms.CheckboxSelectMultiple(),
        to_field_name='title',
        queryset=OperatorNesting.objects.all()
    )
    is_OOP = forms.CheckboxInput()
    is_strings = forms.CheckboxInput()

    def clean(self):
        cleaned_data = super().clean()
        is_if_operator = cleaned_data.get('is_if_operator')
        cycle = cleaned_data.get('cycle')
        is_OOP = cleaned_data.get('is_OOP')
        is_strings = cleaned_data.get('is_strings')

        if not is_if_operator:
            cleaned_data['condition_of_if_operator'] = ConditionType.SIMPLE
        if not cycle:
            cleaned_data['cycle_condition'] = ConditionType.SIMPLE
        is_lock_nesting_of_operators = not (is_if_operator or cycle)
        if is_lock_nesting_of_operators:
            cleaned_data['operator_nesting'] = OperatorNesting.objects.none()
        if is_OOP:
            cleaned_data = self._set_default_basic_fields(cleaned_data)
            cleaned_data['is_strings'] = False
        if is_strings:
            cleaned_data = self._set_default_basic_fields(cleaned_data)
            cleaned_data['is_OOP'] = False

    @staticmethod
    def _set_default_basic_fields(cleaned_data: dict) -> dict:
        cleaned_data['is_if_operator'] = True
        cleaned_data['condition_of_if_operator'] = ConditionType.SIMPLE
        cleaned_data['cycle'] = Cycle.objects.none()
        cleaned_data['cycle_condition'] = ConditionType.SIMPLE
        cleaned_data['operator_nesting'] = OperatorNesting.objects.none()
        return cleaned_data

    class Meta:
        model = Setting
        fields = '__all__'
        exclude = ['users', 'testing_by_code']

src/apps/testing_by_code/forms/solving_task_form.py
from django import forms

from apps.testing_by_code.models import SolvingTask


class SolvingTaskForm(forms.ModelForm):
    answer = forms.CharField(
        label='Ответ',
        required=False,
        widget=forms.TextInput()
    )

    class Meta:
        model = SolvingTask
        fields = ('answer',)

src/apps/testing_by_code/forms/task_form.py
from django import forms

from apps.testing_by_code.models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        widgets = {
            'weight': forms.NumberInput(attrs={
                'class': 'uk-input uk-form-width-small uk-form-small',
                'min': 1,
                'value': 1
            })
        }
        fields = ('weight',)

src/apps/testing_by_code/forms/testing_form.py
from abstractions.abstract_forms import AbstractTestingForm
from apps.testing_by_code.models import Testing


class TestingForm(AbstractTestingForm):
    class Meta(AbstractTestingForm.Meta):
        model = Testing
        exclude = ('date_of_deletion', 'journal', 'total_weight', 'max_score')

src/apps/testing_by_code/templates/testing_by_code/student_solving_testing_detail.html
{% extends "student_solving_testing_detail.html" %}
{% load static %}

{% block description %}
    <h4>
        Определить выводимое на экран значение переменной <br> по результатам выполнения программы на Java:
    </h4>
    <pre onmousedown="return false" class="uk-text-justify"><code>{{ solving_task.code }}</code></pre>
{% endblock %}

src/apps/testing_by_code/templates/testing_by_code/task_form.html
<div hx-target="this" hx-swap="outerHTML">
    <form id="task-form" method="POST">
        {% csrf_token %}
        <div>
            <div class="task__card uk-card uk-card-default uk-card-body">
                <div class="uk-card-header">
                    {% if change_error %}
                        <span id="error" class="error">Ошибка: {{ change_error }}</span>
                    {% endif %}
                    <div class="uk-grid-small uk-flex-middle" uk-grid>
                        <div class="uk-width-expand">
                            <h3 class="uk-card-title uk-margin-remove-bottom">
                                {{ task_form.weight.label }} {{ task_form.weight }}
                                {{ task_form.weight.errors }}
                            </h3>
                        </div>
                    </div>
                </div>
                <div class="task__body body uk-card-body">
                    <h4>Структура программы:</h4>
                    <div>
                        {% for field in setting_form %}
                            <div class="uk-margin">
                                <span>
                                    {{ field.label }}:
                                </span>
                                <div>
                                    {{ field }}
                                    {{ field.errors }}
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="uk-card-footer">
                    {% if task %}
                        <button name="btn-update"
                                type="submit"
                                hx-post="{% url 'testing_by_code:update_task' task.pk %}"
                                uk-icon="refresh"
                                uk-tooltip="Обновить">
                        </button>
                        <button onclick="location.reload()"
                                type="button"
                                uk-icon="close"
                                uk-tooltip="Отмена">
                        </button>
                    {% else %}
                        <button id="btn-add" type="submit"
                                hx-post="."
                                hx-swap="outerHTML"
                                uk-icon="plus"
                                uk-tooltip="Добавить">
                        </button>
                        <button onclick="location.reload()"
                                type="button"
                                uk-icon="close"
                                uk-tooltip="Отмена">
                        </button>
                    {% endif %}
                </div>
            </div>
        </div>
    </form>
</div>

src/apps/testing_by_code/templates/testing_by_code/teacher_testing_detail.html
{% extends "base.html" %}
{% load static %}

{% block head_script %}
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
{% endblock %}

{% block content %}
    {% include 'inc/_testing_settings.html' %}
    {% include 'testing_by_code/inc/task/_teacher_task_list.html' %}
{% endblock %}

{% block script %}
    <script type="text/javascript" src="{% static 'js/testing_by_code/testing_by_code.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/task-form/task-form.js' %}"></script>
    <script type="module" src="{% static 'js/serial_number.js' %}"></script>
{% endblock %}

src/apps/testing_by_code/templates/testing_by_code/testing_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Вы уверены, что хотите удалить "{{ object }}"?</p>
        {{ form }}
        <button class="uk-button uk-button-primary" type="submit" value="Да">Да</button>
        <a class="uk-button uk-button-default" href="{% url 'testing_by_code:testing_detail' testing.pk %}">Отмена</a>
    </form>
{% endblock %}

src/apps/testing_by_code/templates/testing_by_code/testing_detail.html
{% extends "base.html" %}
{% load static %}

{% block head_script %}
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/testing_by_code/testing_by_code.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/task-form/task-form.js' %}"></script>
{% endblock %}
{% block content %}
    {% include 'inc/_testing_settings.html' %}
    {% if user.is_teacher %}
        {% include 'testing_by_code/inc/task/_teacher_task_list.html' %}
    {% else %}
        {% include 'testing_by_code/inc/task/_student_task_list.html' %}
    {% endif %}
{% endblock %}

src/apps/testing_by_code/templates/testing_by_code/testing_form.html
<div hx-target="this" hx-swap="outerHTML">
    <form class="form" method="POST">
        {% csrf_token %}
        <section class="form__testing testing">
            <h2 class="testing__title">
                Создать настройки задач для тестирования
                {{ form.title }}
                {{ form.title.errors }}
            </h2>
            <div class="testing__student-group">
                {{ form.student_group.label }}
                {{ form.student_group }}
                {{ form.student_group.errors }}
            </div>
        </section>
        <button type="submit" hx-post="{% url 'testing_by_code:update_testing' testing.id %}"
                hx-target="#wrapper"
                hx-swap="outerHTML"
                uk-icon="refresh"
                uk-tooltip="Обновить">
        </button>
        <button type="button"
                hx-get="{% url 'testing_by_code:setting_detail' testing.id %}"
                uk-icon="close"
                uk-tooltip="Отмена">
        </button>
    </form>
</div>