src/apps/testing/urls.py
from django.urls import path

from .constants import APP_NAME
from .views.task_views import TaskDeleteView
from .views.task_views.closed_question_views import ClosedQuestionCreateView, ClosedQuestionUpdateView, \
    ClosedQuestionDetailView
from .views.task_views.open_question_views import OpenQuestionCreateView, OpenQuestionUpdateView, OpenQuestionDetailView
from .views.task_views.sequencing_views import SequencingCreateView, SequencingUpdateView
from .views.task_views.sequencing_views.sequencing_detail_view import SequencingDetailView
from .views.testing_views import TestingCreateView, TestingUpdateView, TestingDeleteView, TeacherTestingDetailView, \
    StudentSolvingTestingDetailView
from .views.testing_views.testing_detail_view import redirect_testing_detail_view

app_name = APP_NAME
urlpatterns = [
    path('journal/<journal_pk>/create', TestingCreateView.as_view(), name='testing_create'),
    path('<pk>/redirect_detail', redirect_testing_detail_view, name='testing_detail'),
    path('<pk>/detail', TeacherTestingDetailView.as_view(), name='teacher_testing_detail'),
    path('<pk>/solving_task_list', StudentSolvingTestingDetailView.as_view(), name='student_testing_detail'),

    path('update/<pk>', TestingUpdateView.as_view(), name='testing_update'),
    path('delete/<pk>', TestingDeleteView.as_view(), name='testing_delete'),

    path('<testing_pk>/task/closed_question/<type>/create', ClosedQuestionCreateView.as_view(),
         name='task_closed_question_create'),
    path('task/closed_question/detail/<pk>', ClosedQuestionDetailView.as_view(),
         name='task_closed_question_detail'),
    path('task/closed_question/update/<pk>', ClosedQuestionUpdateView.as_view(),
         name='task_closed_question_update'),

    path('<testing_pk>/task/open_question/<type>/create', OpenQuestionCreateView.as_view(),
         name='task_open_question_create'),
    path('task/open_question/detail/<pk>', OpenQuestionDetailView.as_view(),
         name='task_open_question_detail'),
    path('task/open_question/update/<pk>', OpenQuestionUpdateView.as_view(),
         name='task_open_question_update'),

    path('<testing_pk>/task/sequencing/<type>/create', SequencingCreateView.as_view(),
         name='task_sequencing_create'),
    path('task/sequencing/detail/<pk>', SequencingDetailView.as_view(),
         name='task_sequencing_detail'),
    path('task/sequencing/update/<pk>', SequencingUpdateView.as_view(),
         name='task_sequencing_update'),

    path('task/delete/<pk>', TaskDeleteView.as_view(), name='task_delete'),
]

src/apps/testing_by_code/urls.py
from django.urls import path

from .views.solving_testing_views import StudentSolvingTestingDetailView
from .views.task_views import TaskDetailView, update_task, duplicate_task, delete_task, add_task_form, \
    update_tasks_serial_number_view
from .views.testing_views import TestingCreateView, TestingUpdateView, \
    TestingDeleteView, TeacherTestingDetailView
from .views.testing_views.testing_detail_view import redirect_testing_detail_view

app_name = 'testing_by_code'
urlpatterns = [
    path('journal/<journal_pk>/create/', TestingCreateView.as_view(), name='testing_create'),
    path('<pk>/redirect_detail/', redirect_testing_detail_view, name='testing_detail'),
    path('<pk>/detail/', TeacherTestingDetailView.as_view(), name='teacher_testing_detail'),
    path('<pk>/solving_task_list/', StudentSolvingTestingDetailView.as_view(), name='student_testing_detail'),

    path('<pk>/update/', TestingUpdateView.as_view(), name='testing_update'),
    path('<pk>/delete/', TestingDeleteView.as_view(), name='testing_delete'),
    path('task/<pk>/detail/', TaskDetailView.as_view(), name='task_detail'),
    path('task/<pk>/update/', update_task, name='update_task'),
    path('task/<pk>/duplicate/', duplicate_task, name='duplicate_task'),
    path('task/<pk>/delete/', delete_task, name='delete_task'),
    path('add_task_form/', add_task_form, name='add_task_form'),
    path('<pk>/update_tasks_serial_number/', update_tasks_serial_number_view, name='update_tasks_serial_number'),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('', include('apps.user.urls', namespace='user')),
    path('testing/', include('apps.testing.urls', namespace='testing')),
    path('testing_by_code/', include('apps.testing_by_code.urls', namespace='testing_by_code')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('pwa.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    from django.urls import re_path
    from django.views.static import serve

    urlpatterns += [re_path(r'media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}), ]

src/apps/testing/models/max_score.py
from typing import Iterable

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from apps.testing.constants import APP_NAME


class MaxScore(models.Model):
    five = models.IntegerField(
        default=100,
        validators=[
            MaxValueValidator(100),
            MinValueValidator(1)
        ],
        verbose_name='Отлично'
    )
    four = models.IntegerField(
        default=80,
        validators=[
            MaxValueValidator(100),
            MinValueValidator(1)
        ],
        verbose_name='Хорошо'
    )
    three = models.IntegerField(
        default=60,
        validators=[
            MaxValueValidator(100),
            MinValueValidator(1)
        ],
        verbose_name='Удовлетворительно'
    )
    two = models.IntegerField(
        default=40,
        validators=[
            MaxValueValidator(100),
            MinValueValidator(1)
        ],
        verbose_name='Неудовлетворительно'
    )

    def get_fields(self) -> Iterable:
        from apps.testing.services import get_model_fields
        return get_model_fields(
            model=self,
            excluded_fields=['id']
        )

    class Meta:
        db_table = f'{APP_NAME}_max-score'

src/apps/testing/models/solving_task.py
from django.db import models
from django.db.models import QuerySet, Case, When, BooleanField, Value

from abstractions.abstract_models import AbstractSolvingTask
from apps.testing.constants import APP_NAME
from apps.testing.types import TaskType


class SolvingTask(AbstractSolvingTask):
    RELATED_NAME = 'solving_task_set'

    answer = models.JSONField(null=True, blank=True, verbose_name='Ответ')
    score = models.FloatField(default=0.0, verbose_name='Балл')
    task = models.ForeignKey(
        'Task',
        on_delete=models.CASCADE,
        related_name=RELATED_NAME,
        verbose_name='Задача'
    )
    solving_testing = models.ForeignKey(
        'SolvingTesting',
        on_delete=models.CASCADE,
        related_name=RELATED_NAME,
        verbose_name='Решение тестирования'
    )

    @property
    def selected_answer_options_template(self) -> str:
        return f'testing/inc/selected_answer_options/_selected_answer_options_{self.task.en_type}.html'

    @property
    def selected_answer_options(self) -> None | str | QuerySet:
        if not self.answer:
            return None
        task = self.task
        match task.type:
            case TaskType.CLOSED_QUESTION:
                return task.answer_option_set.all().annotate(
                    is_selected=Case(
                        When(id__in=self.answer, then=Value(True)),
                        default=Value(False),
                        output_field=BooleanField()
                    )
                )
            case TaskType.SEQUENCING:
                preserved = Case(*[When(pk=pk, then=pos) for pos, pk in enumerate(self.answer)])
                return task.answer_option_set.filter(pk__in=self.answer).order_by(preserved)
            case TaskType.OPEN_QUESTION:
                return self.answer

    class Meta:
        db_table = f'{APP_NAME}_solving-task'
        ordering = ('task__serial_number',)

src/apps/testing/models/solving_testing.py
from abstractions.abstract_models import AbstractSolvingTesting
from apps.testing.constants import APP_NAME


class SolvingTesting(AbstractSolvingTesting):
    class Meta(AbstractSolvingTesting.Meta):
        db_table = f'{APP_NAME}_solving-testing'

src/apps/testing/models/task.py
from django.db import models
from django.db.models import QuerySet
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from abstractions.abstract_models import AbstractTask
from apps.testing.constants import APP_NAME
from apps.testing.interfaces import ITaskService
from apps.testing.types import TaskType
from config.settings import MAX_LENGTH


class Task(AbstractTask):
    TASKS_TYPES_CHOICES = [(type.value, _(type.value)) for type in TaskType]

    type = models.CharField(
        max_length=MAX_LENGTH,
        null=False,
        choices=TASKS_TYPES_CHOICES,
        verbose_name='Тип'
    )
    testing = models.ForeignKey(
        'Testing',
        on_delete=models.CASCADE,
        verbose_name='Тестирование'
    )

    @property
    def service(self) -> ITaskService:
        from apps.testing.services import ClosedQuestionService, OpenQuestionService, SequencingService
        match self.type:
            case TaskType.CLOSED_QUESTION:
                return ClosedQuestionService(self)
            case TaskType.OPEN_QUESTION:
                return OpenQuestionService(self)
            case TaskType.SEQUENCING:
                return SequencingService(self)

    @property
    def additional_model(self) -> QuerySet | None:
        if self.type == TaskType.CLOSED_QUESTION:
            return self.closed_question_set
        else:
            return None

    @property
    def task_type(self) -> TaskType:
        return TaskType(self.type)

    @property
    def en_type(self) -> str:
        return self.task_type.en_value

    def get_absolute_url(self) -> reverse:
        kwargs = {'pk': self.pk}
        if self.testing.testing_solving_testing_set.exists():
            return reverse(f'{APP_NAME}:task_{self.en_type}_detail', kwargs=kwargs)
        else:
            return reverse(f'{APP_NAME}:task_{self.en_type}_update', kwargs=kwargs)

    def get_deletion_url(self) -> reverse:
        return reverse(f'{APP_NAME}:task_delete', kwargs={'pk': self.pk})

src/apps/testing/models/testing.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.urls import reverse

from abstractions.abstract_models import AbstractTesting
from apps.base_testing.constants import MAX_ASSESSMENT_THRESHOLD, MIN_ASSESSMENT_THRESHOLD


class Testing(AbstractTesting):
    number = models.IntegerField(
        default=1,
        verbose_name='Номер работы'
    )
    probability_of_guessing = models.FloatField(
        default=1,
        verbose_name='Вероятность угадывания'
    )
    assessment_threshold = models.IntegerField(
        default=1,
        validators=[
            MaxValueValidator(MAX_ASSESSMENT_THRESHOLD),
            MinValueValidator(MIN_ASSESSMENT_THRESHOLD)
        ],
        verbose_name='Пороговое значение оценки'
    )

    def get_absolute_url(self):
        return reverse(f'testing:testing_detail', kwargs={'pk': self.pk})

    def get_student_absolute_url(self) -> reverse:
        return reverse(f'testing:student_testing_detail', kwargs={'pk': self.pk})

    def is_solving_testing_set(self) -> bool:
        return self.testing_solving_testing_set.exists()

src/apps/testing_by_code/models/task.py
from django.db import models

from abstractions.abstract_fields import AbstractFieldWeight
from abstractions.abstract_models import AbstractTask


class Task(AbstractFieldWeight, AbstractTask):
    RELATED_NAME = 'task_set'

    testing = models.ForeignKey(
        'Testing',
        related_name=RELATED_NAME,
        on_delete=models.CASCADE,
        verbose_name='Тестирование'
    )
    setting = models.ForeignKey(
        'Setting',
        related_name=RELATED_NAME,
        on_delete=models.CASCADE,
        verbose_name='Настройка'
    )

    class Meta(AbstractTask.Meta):
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'

src/apps/testing_by_code/models/testing.py
from django.db import models
from django.db.models import Sum
from django.urls import reverse

from abstractions.abstract_models.abstract_testing import AbstractTesting


class Testing(AbstractTesting):
    total_weight = models.IntegerField(default=0, verbose_name='Общий вес')

    def get_absolute_url(self) -> reverse:
        return reverse('testing_by_code:testing_detail', kwargs={'pk': self.pk})

    def get_student_absolute_url(self) -> reverse:
        return reverse(f'testing_by_code:student_testing_detail', kwargs={'pk': self.pk})

    def get_total_weight(self) -> int:
        return self.task_set.aggregate(
            total_weight=Sum('weight')
        )['total_weight']

    def is_solving_testing_set(self) -> bool:
        return self.testing_by_code_solving_testing_set.exists()

    def __str__(self):
        return self.title

    class Meta(AbstractTesting.Meta):
        pass

src/apps/testing/forms/max_score_form.py
from django import forms

from apps.testing.constants import MIN_ASSESSMENT_THRESHOLD, MAX_ASSESSMENT_THRESHOLD
from apps.testing.models import MaxScore


class MaxScoreForm(forms.ModelForm):
    class Meta:
        model = MaxScore
        number_input = forms.NumberInput(attrs={
            'class': 'uk-margin-small uk-input uk-width-small',
            'min': MIN_ASSESSMENT_THRESHOLD,
            'max': MAX_ASSESSMENT_THRESHOLD
        })
        widgets = {
            'five': number_input,
            'four': number_input,
            'three': number_input,
            'two': number_input
        }
        fields = '__all__'

src/apps/testing/forms/testing_form.py
from django import forms

from abstractions.abstract_forms import AbstractTestingForm
from apps.base_testing.constants import MIN_ASSESSMENT_THRESHOLD, MAX_ASSESSMENT_THRESHOLD
from apps.testing.constants import MAX_PROBABILITY_OF_GUESSING
from apps.testing.models import Testing


class TestingForm(AbstractTestingForm):
    class Meta(AbstractTestingForm.Meta):
        CLASS = 'uk-margin-small uk-input uk-width-small'
        model = Testing
        widgets = AbstractTestingForm.Meta.widgets | {
            'number': forms.NumberInput(attrs={
                'class': CLASS,
            }),
            'probability_of_guessing': forms.NumberInput(attrs={
                'class': CLASS,
                'max': MAX_PROBABILITY_OF_GUESSING,
                'min': 0,
                'step': '0.01'
            }),
            'assessment_threshold': forms.NumberInput(attrs={
                'class': CLASS,
                'min': MIN_ASSESSMENT_THRESHOLD,
                'max': MAX_ASSESSMENT_THRESHOLD,
            }),
        }
        exclude = ('date_of_deletion', 'max_score', 'journal')

src/apps/testing_by_code/forms/task_form.py
from django import forms

from apps.testing_by_code.models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        widgets = {
            'weight': forms.NumberInput(attrs={
                'class': 'uk-input uk-form-width-small uk-form-small',
                'min': 1,
                'value': 1
            })
        }
        fields = ('weight',)

src/apps/testing_by_code/forms/testing_form.py
from abstractions.abstract_forms import AbstractTestingForm
from apps.testing_by_code.models import Testing


class TestingForm(AbstractTestingForm):
    class Meta(AbstractTestingForm.Meta):
        model = Testing
        exclude = ('date_of_deletion', 'journal', 'total_weight', 'max_score')

src/testing/templates/testing/inc/task/_detail.html
{% load model_manipulation %}

<div class="task" hx-target="this">
    {% with task.setting as setting %}
        <div>
            <div class="task__card uk-card uk-card-default uk-card-body">
                <div class="uk-card-header">
                    <div class="uk-grid-small uk-flex-middle" uk-grid>
                        <div class="uk-width-expand">
                            <h3 class="uk-card-title uk-margin-remove-bottom">
                                Задача №<span class="task-number">{{ task_number }}</span> (вес {{ task.weight }})
                            </h3>
                        </div>
                    </div>
                </div>
                <div class="task__body body uk-card-body">
                    <h4>Структура программы:</h4>
                    <div class="uk-text-justify">
                        <div>
                            <div class="uk-margin">
                                <span>
                                    {% get_verbose_name_for_field setting 'is_if_operator' %}:
                                </span>
                                <div>
                                    {{ setting.is_if_operator }}
                                </div>
                            </div>
                            <div class="uk-margin">
                                <span>
                                    {% get_verbose_name_for_field setting 'condition_of_if_operator' %}:
                                </span>
                                <div>
                                    {{ setting.condition_of_if_operator }}
                                </div>
                            </div>
                            <div class="uk-margin">
                                <span>
                                    {% get_verbose_name_for_field setting 'cycle' %}:
                                </span>
                                <div>
                                    {% with setting.cycle.all as cycles %}
                                        {% if cycles %}
                                            {{ cycles|join:', ' }}
                                        {% else %}
                                            Не выбрано
                                        {% endif %}
                                    {% endwith %}
                                </div>
                            </div>
                            <div class="uk-margin">
                                <span>
                                    {% get_verbose_name_for_field setting 'cycle_condition' %}:
                                </span>
                                <div>
                                    {{ setting.cycle_condition }}
                                </div>
                            </div>
                            <div class="uk-margin">
                                <span>
                                    {% get_verbose_name_for_field setting 'operator_nesting' %}:
                                </span>
                                <div>
                                    {% with setting.operator_nesting.all as operators_nesting %}
                                        {% if operators_nesting %}
                                            {{ operators_nesting|join:', ' }}
                                        {% else %}
                                            Не выбрано
                                        {% endif %}
                                    {% endwith %}
                                </div>
                            </div>
                        </div>
                        <div class="uk-margin">
                                <span>
                                    {% get_verbose_name_for_field setting 'is_OOP' %}:
                                </span>
                            <div>
                                {% if setting.is_OOP %}
                                    Есть
                                {% else %}
                                    Нет
                                {% endif %}
                            </div>
                        </div>
                        <div class="uk-margin">
                                <span>
                                    {% get_verbose_name_for_field setting 'is_strings' %}:
                                </span>
                            <div>
                                {% if setting.is_strings %}
                                    Есть
                                {% else %}
                                    Нет
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="uk-card-footer">
                    <button class="btn-update"
                            hx-post="{% url 'testing:update_task' task.pk %}"
                            hx-swap="outerHTML"
                            uk-icon="refresh"
                            uk-tooltip="Обновить">
                    </button>
                    <button class="btn-duplicate"
                            hx-post="{% url 'testing:duplicate_task' task.pk %}"
                            hx-swap="beforebegin"
                            uk-icon="copy"
                            uk-tooltip="Дублировать">
                    </button>
                    <button class="btn-delete"
                            hx-post="{% url 'testing:delete_task' task.pk %}"
                            hx-swap="outerHTML"
                            uk-icon="trash"
                            uk-tooltip="Удалить">
                    </button>
                </div>
            </div>
        </div>
    {% endwith %}
</div>

src/testing/templates/testing/inc/task/_list.html
<section
        class="content__task-list task-list uk-text-left uk-child-width-1-2@s uk-child-width-1-3@m uk-child-width-1-4@l"
        id="task-list" uk-grid>
    {% for task in testing.task_set.all %}
        {% for i in 'n'|rjust:task.count %}
            {% include "testing/inc/task/_detail.html" %}
        {% endfor %}
    {% endfor %}
</section>

src/testing/templates/testing/inc/task/_student-detail.html
<div class="task-student-list__task task uk-text-left uk-grid-match" hx-target="this">
    <div>
        <div class="task__card uk-card uk-card-default uk-card-body">
            <div class="uk-card-header">
                <div class="uk-grid-small uk-flex-middle" uk-grid>
                    <div class="uk-width-expand">
                        <h3 class="uk-card-title uk-margin-remove-bottom">
                            Задача №<span class="task-number">{{ task_number }}</span> (вес {{ values.weight }})
                            <input name="weight" type="hidden" value="{{ values.weight|add:"0" }}">
                        </h3>
                    </div>
                </div>
            </div>
            <div class="uk-card-body">
                <h4>
                    Определить выводимое на экран значение переменной <br> по результатам выполнения программы на Java:
                </h4>
                <pre onmousedown="return false"
                     class="task__code uk-text-justify"><code>{{ values.code }}</code></pre>
                <input name="code" type="hidden" value="{{ values.code }}">
                <p>
                    Ваш ответ: <input class="uk-input uk-form-width-medium uk-form-small" name="answer" type="text"
                                      required>
                </p>
            </div>
        </div>
    </div>
</div>

src/testing/templates/testing/inc/task/_student-list.html
<section class="content__task-student-list task-student-list uk-flex uk-flex-column"
         id="task-student-list">
    <form action="{% url 'testing:completed_testing_create' %}" method="get">
        {% csrf_token %}
        <input name="testing_title" type="hidden" value="{{ testing.title }}">
        <input name="testing_start_passage" type="hidden" value="{{ start_passage }}">
        <input name="testing_is_review_of_result_by_student" type="hidden"
               value="{{ testing.is_review_of_result_by_student }}">
        <input name="testing_pk" type="hidden" value="{{ testing.pk }}">
        <button class="uk-margin uk-button uk-button-primary" type="submit">Завершить тест</button>
        <div class="uk-grid-match uk-child-width-1-3@m" uk-grid>
            {% for key, values in task_data.items %}
                {% include "testing/inc/task/_student-detail.html" %}
            {% endfor %}
        </div>
    </form>
</section>

src/testing/templates/testing/inc/task/_tecaher_task_detail.html
{% load model_manipulation %}

<div class="task" hx-target="this">
    {% with task.setting as setting %}
        <div>
            <div class="task__card uk-card uk-card-default uk-card-body">
                <div class="uk-card-header">
                    <div class="uk-grid-small uk-flex-middle" uk-grid>
                        <div class="uk-width-expand">
                            <h3 class="uk-card-title uk-margin-remove-bottom">
                                Задача №<span class="task-number">{{ task_number }}</span> (вес {{ task.weight }})
                            </h3>
                        </div>
                    </div>
                </div>
                <div class="task__body body uk-card-body">
                    <h4>Структура программы:</h4>
                    <div class="uk-text-justify">
                        <div>
                            <div class="uk-margin">
                                <span>
                                    {% get_verbose_name_for_field setting 'is_if_operator' %}:
                                </span>
                                <div>
                                    {{ setting.is_if_operator }}
                                </div>
                            </div>
                            <div class="uk-margin">
                                <span>
                                    {% get_verbose_name_for_field setting 'condition_of_if_operator' %}:
                                </span>
                                <div>
                                    {{ setting.condition_of_if_operator }}
                                </div>
                            </div>
                            <div class="uk-margin">
                                <span>
                                    {% get_verbose_name_for_field setting 'cycle' %}:
                                </span>
                                <div>
                                    {% with setting.cycle.all as cycles %}
                                        {% if cycles %}
                                            {{ cycles|join:', ' }}
                                        {% else %}
                                            Не выбрано
                                        {% endif %}
                                    {% endwith %}
                                </div>
                            </div>
                            <div class="uk-margin">
                                <span>
                                    {% get_verbose_name_for_field setting 'cycle_condition' %}:
                                </span>
                                <div>
                                    {{ setting.cycle_condition }}
                                </div>
                            </div>
                            <div class="uk-margin">
                                <span>
                                    {% get_verbose_name_for_field setting 'operator_nesting' %}:
                                </span>
                                <div>
                                    {% with setting.operator_nesting.all as operators_nesting %}
                                        {% if operators_nesting %}
                                            {{ operators_nesting|join:', ' }}
                                        {% else %}
                                            Не выбрано
                                        {% endif %}
                                    {% endwith %}
                                </div>
                            </div>
                        </div>
                        <div class="uk-margin">
                                <span>
                                    {% get_verbose_name_for_field setting 'is_OOP' %}:
                                </span>
                            <div>
                                {% if setting.is_OOP %}
                                    Есть
                                {% else %}
                                    Нет
                                {% endif %}
                            </div>
                        </div>
                        <div class="uk-margin">
                                <span>
                                    {% get_verbose_name_for_field setting 'is_strings' %}:
                                </span>
                            <div>
                                {% if setting.is_strings %}
                                    Есть
                                {% else %}
                                    Нет
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="uk-card-footer">
                    <button class="btn-update"
                            hx-post="{% url 'testing:update_task' task.pk %}"
                            hx-swap="outerHTML"
                            uk-icon="refresh"
                            uk-tooltip="Обновить">
                    </button>
                    <button class="btn-duplicate"
                            hx-post="{% url 'testing:duplicate_task' task.pk %}"
                            hx-swap="beforebegin"
                            uk-icon="copy"
                            uk-tooltip="Дублировать">
                    </button>
                    <button class="btn-delete"
                            hx-post="{% url 'testing:delete_task' task.pk %}"
                            hx-swap="outerHTML"
                            uk-icon="trash"
                            uk-tooltip="Удалить">
                    </button>
                </div>
            </div>
        </div>
    {% endwith %}
</div>