src/apps/testing/urls.py
from django.urls import path

from .constants import APP_NAME
from .views.task_views import TaskDeleteView
from .views.task_views.closed_question_views import ClosedQuestionCreateView, ClosedQuestionUpdateView, \
    ClosedQuestionDetailView
from .views.task_views.open_question_views import OpenQuestionCreateView, OpenQuestionUpdateView, OpenQuestionDetailView
from .views.task_views.sequencing_views import SequencingCreateView, SequencingUpdateView
from .views.task_views.sequencing_views.sequencing_detail_view import SequencingDetailView
from .views.testing_views import TestingCreateView, TestingUpdateView, TestingDeleteView, TeacherTestingDetailView, \
    StudentSolvingTestingDetailView
from .views.testing_views.testing_detail_view import redirect_testing_detail_view

app_name = APP_NAME
urlpatterns = [
    path('journal/<journal_pk>/create', TestingCreateView.as_view(), name='testing_create'),
    path('<pk>/redirect_detail', redirect_testing_detail_view, name='testing_detail'),
    path('<pk>/detail', TeacherTestingDetailView.as_view(), name='teacher_testing_detail'),
    path('<pk>/solving_task_list', StudentSolvingTestingDetailView.as_view(), name='student_testing_detail'),

    path('update/<pk>', TestingUpdateView.as_view(), name='testing_update'),
    path('delete/<pk>', TestingDeleteView.as_view(), name='testing_delete'),

    path('<testing_pk>/task/closed_question/<type>/create', ClosedQuestionCreateView.as_view(),
         name='task_closed_question_create'),
    path('task/closed_question/detail/<pk>', ClosedQuestionDetailView.as_view(),
         name='task_closed_question_detail'),
    path('task/closed_question/update/<pk>', ClosedQuestionUpdateView.as_view(),
         name='task_closed_question_update'),

    path('<testing_pk>/task/open_question/<type>/create', OpenQuestionCreateView.as_view(),
         name='task_open_question_create'),
    path('task/open_question/detail/<pk>', OpenQuestionDetailView.as_view(),
         name='task_open_question_detail'),
    path('task/open_question/update/<pk>', OpenQuestionUpdateView.as_view(),
         name='task_open_question_update'),

    path('<testing_pk>/task/sequencing/<type>/create', SequencingCreateView.as_view(),
         name='task_sequencing_create'),
    path('task/sequencing/detail/<pk>', SequencingDetailView.as_view(),
         name='task_sequencing_detail'),
    path('task/sequencing/update/<pk>', SequencingUpdateView.as_view(),
         name='task_sequencing_update'),

    path('task/delete/<pk>', TaskDeleteView.as_view(), name='task_delete'),
]

src/apps/testing_by_code/urls.py
from django.urls import path

from .views.solving_testing_views import StudentSolvingTestingDetailView
from .views.task_views import TaskDetailView, update_task, duplicate_task, delete_task, add_task_form, \
    update_tasks_serial_number_view
from .views.testing_views import TestingCreateView, TestingUpdateView, \
    TestingDeleteView, TeacherTestingDetailView
from .views.testing_views.testing_detail_view import redirect_testing_detail_view

app_name = 'testing_by_code'
urlpatterns = [
    path('journal/<journal_pk>/create/', TestingCreateView.as_view(), name='testing_create'),
    path('<pk>/redirect_detail/', redirect_testing_detail_view, name='testing_detail'),
    path('<pk>/detail/', TeacherTestingDetailView.as_view(), name='teacher_testing_detail'),
    path('<pk>/solving_task_list/', StudentSolvingTestingDetailView.as_view(), name='student_testing_detail'),

    path('<pk>/update/', TestingUpdateView.as_view(), name='testing_update'),
    path('<pk>/delete/', TestingDeleteView.as_view(), name='testing_delete'),
    path('task/<pk>/detail/', TaskDetailView.as_view(), name='task_detail'),
    path('task/<pk>/update/', update_task, name='update_task'),
    path('task/<pk>/duplicate/', duplicate_task, name='duplicate_task'),
    path('task/<pk>/delete/', delete_task, name='delete_task'),
    path('add_task_form/', add_task_form, name='add_task_form'),
    path('<pk>/update_tasks_serial_number/', update_tasks_serial_number_view, name='update_tasks_serial_number'),
]

src/apps/user/urls.py
from django.urls import path

from apps.user.constants import APP_NAME
from apps.user.views import LoginUser, CustomLogoutView, TestingListView, SolvingTestingListView
from apps.user.views.journal_views import TestingSettingJournalView, TestingResultJournalView, StudentJournalView
from apps.user.views.student_views import StudentTemplateView
from apps.user.views.teacher_views import TeacherTemplateView

app_name = APP_NAME

urlpatterns = [
    path('', LoginUser.as_view(), name='home'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),

    path('student/', StudentTemplateView.as_view(), name='student_detail'),
    path('journal/student/', StudentJournalView.as_view(),
         name='student_journal'),

    path('teacher/', TeacherTemplateView.as_view(), name='teacher_detail'),

    path('journal/<journal_pk>/testing_list_view/', TestingListView.as_view(), name='testing_list'),
    path('journal/<journal_pk>/student/<student_pk>/solving_testing_list_view/', SolvingTestingListView.as_view(),
         name='solving_testing_list'),

    path('journal/testing_setting_journal/', TestingSettingJournalView.as_view(),
         name='testing_setting_journal'),
    path('journal/testing_result_journal/', TestingResultJournalView.as_view(),
         name='testing_result_journal'),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('', include('apps.user.urls', namespace='user')),
    path('testing/', include('apps.testing.urls', namespace='testing')),
    path('testing_by_code/', include('apps.testing_by_code.urls', namespace='testing_by_code')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('pwa.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    from django.urls import re_path
    from django.views.static import serve

    urlpatterns += [re_path(r'media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}), ]

src/apps/user/models/student_group.py
from django.db import models
from django.urls import reverse

from apps.user.constants import APP_NAME
from apps.user.models import EducationalEstablishment


class StudentGroup(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name='Название')
    year_start_studying = models.IntegerField(verbose_name='Год начала обучения')
    year_end_studying = models.IntegerField(verbose_name='Год окончания обучения')
    specialty = models.CharField(max_length=50, blank=True, verbose_name='Специальность')
    educational_establishment = models.ForeignKey(
        EducationalEstablishment,
        on_delete=models.CASCADE,
        related_name='student_group_set',
        verbose_name='Образовательное учреждение'
    )

    def get_absolute_url(self):
        return reverse('student_group_detail', kwargs={"pk": self.pk})

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Группа студента'
        verbose_name_plural = 'Группы студентов'
        db_table = f'{APP_NAME}_student-group'

src/apps/user/views/testing_list_view.py
from itertools import chain
from operator import attrgetter

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView

from apps.testing.models import Testing
from apps.testing_by_code.models import Testing as TestingByCode


@method_decorator(login_required, name='dispatch')
class TestingListView(TemplateView):
    template_name = 'testing_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_teacher():
            text = 'Настроить тестирование'
        else:
            text = 'Пройти тест'
        context |= {
            'text': text,
            'testing_list': self._get_testings(journal_pk=kwargs['journal_pk'])
        }
        return context

    @staticmethod
    def _get_testings(journal_pk: int | str):
        models = [Testing, TestingByCode]
        orm_filter = {'journal': journal_pk}
        testings = [model.objects.filter(**orm_filter) for model in models]
        sorted_testings = sorted(
            chain(*testings),
            key=attrgetter('date_of_creation'),
            reverse=True,
        )
        return sorted_testings

src/templates/inc/_header.html
<header class="header uk-padding-small uk-padding-remove-bottom">
    <nav class="header__menu">
        <ul class="header__list uk-nav-default uk-nav-parent-icon" uk-nav>
            <li>
                <a href="/">
                    <span class="uk-margin-small-right" uk-icon="icon:  home"></span> Главная
                </a>
            </li>
            {% if request.user.is_authenticated %}
                <li class="header__link">
                    <a href="{% url 'user:logout' %}">
                        <span class="uk-margin-small-right" uk-icon="icon: trash"></span> Выйти
                    </a>
                </li>
                <li class="uk-nav-divider"></li>
            {% endif %}
        </ul>
    </nav>
</header>

src/templates/inc/_student_groups.html
<div class="uk-card-body">
    {% if student_groups %}
        <p>Группы: {{ student_groups|join:', ' }}</p>
    {% else %}
        <p>Группы: не выбраны</p>
    {% endif %}
</div>

src/templates/inc/_testing_detail_buttons.html
<div name="btns-testing" class="uk-flex uk-flex-column">
    {% if not is_solving_testing %}
        <div class="uk-margin-small-top">
            <a class="uk-width-1-5 uk-button uk-button-primary"
               href="{% url testing_update_url testing.pk %}"
               id="btn-update-testing">
                Обновить тестирование
            </a>
        </div>
    {% endif %}
    <div class="uk-margin-small-top">
        <form action="{% url testing_delete_url testing.pk %}">
            {% csrf_token %}
            <button type="submit" class="uk-width-1-5 uk-button uk-button-danger">
                Удалить тестирование
            </button>
        </form>
    </div>
    {% if not is_solving_testing %}
        <div class="uk-margin-small-top">
            {% if tasks_types %}
                {% include 'testing/inc/testing/_add_task_button.html' %}
            {% else %}
                {% include 'testing_by_code/inc/testing/_add_task_button.html' %}
            {% endif %}
        </div>
        <div class="uk-margin-small-top">
            <form id="serial-number-update-form"
                  action="{% url 'testing_by_code:update_tasks_serial_number' testing.id %}"
                  method="post">
                {% csrf_token %}
                <button class="uk-button uk-button-primary" type="submit">Обновить нумерацию задач</button>
            </form>
        </div>
    {% endif %}
</div>

src/templates/inc/_testing_fields.html
{% load filters %}
{% for field, value in testing.get_fields_data.items %}
    {% if field == 'Наименование' %}
        <h2>
            Настройки тестирования {{ value }}
        </h2>
    {% elif field == 'Группы студентов' %}
        <div class="header__student-groups uk-text-center">
            <ul class="uk-margin-small" uk-accordion>
                <li>
                    {% if value %}
                        <a class="uk-accordion-title" href="#">Группы студентов</a>
                        <div class="uk-accordion-content">
                            {% for student_group in value %}
                                <div>
                                    {{ student_group.name }}
                                </div>
                            {% endfor %}
                        </div>
                    {% else %}
                        Группы студентов не выбраны
                    {% endif %}
                </li>
            </ul>
        </div>
    {% else %}
        <div>
            {{ field }}: {{ value }}
        </div>
    {% endif %}
{% endfor %}
<div>Максимальный балл</div>
{% with testing.max_score as max_score %}
    {% for field in max_score.get_fields %}
        <div>
            {{ field.verbose_name }}: {{ max_score|get_attr:field.name }}
        </div>
        {% empty %}
        <div>Не задан</div>
    {% endfor %}
{% endwith %}

src/templates/inc/_testing_list.html
{% if testing_list %}
    <div class="uk-margin-top uk-grid-match uk-grid-column-small uk-grid-row-large uk-child-width-1-3@s uk-text-center"
         uk-grid>
        {% for testing in testing_list %}
            <div>
                <div class="uk-card uk-card-default uk-card-body">
                    <div class="uk-card-header">
                        <div class="uk-grid-small uk-flex-middle" uk-grid>
                            <div class="uk-width-expand">
                                <h3 class="uk-card-title uk-margin-remove-bottom">
                                    {{ testing.title }}
                                </h3>
                            </div>
                        </div>
                    </div>
                    {% if user.is_teacher %}
                        {% include "inc/_student_groups.html" with student_groups=testing.student_groups.all %}
                    {% endif %}
                    <div class="uk-card-footer">
                        <a href="{{ testing.get_absolute_url }}" class="uk-button uk-button-text">
                            {{ text }}
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% else %}
    <h1 class="uk-text-danger">Нет доступных тестов</h1>
{% endif %}

src/templates/inc/_testing_list_buttons.html
<form class="uk-margin" action="{% url 'user:testing_list' journal_pk %}">
    <label>
        <input class="uk-input uk-width-1-4" name="search" type="text" placeholder="Поиск" required>
    </label>
    <button class="uk-search-toggle" uk-search-icon type="submit" uk-tooltip="Поиск"></button>
</form>
<form action="{% url 'user:testing_list' journal_pk %}">
    <button class="uk-margin uk-button uk-button-primary" type="submit">
        Показать все тесты
    </button>
</form>
{% if user.is_teacher %}
    <a class="uk-button uk-button-primary" href="{% url 'testing:testing_create' journal_pk %}">
        Добавить тестирование
    </a>
    <a class="uk-button uk-button-primary" href="{% url 'testing_by_code:testing_create' journal_pk %}">
        Добавить тестирование по коду
    </a>
{% endif %}

src/templates/inc/_testing_settings.html
<section class='content__testing-settings' id='testing-settings'>
    {% if user.is_teacher %}
        {% if is_solving_testing %}
            <span class="error">
            Данное тестирование нельзя настроить. Кто-то из студентов его прошёл. <br> Его можно только удалить. Результаты студентов, которые прошли тестирование, останутся нетронутыми.
            </span>
        {% endif %}
        {% include 'inc/_testing_fields.html' %}
        {% include 'inc/_testing_detail_buttons.html' %}
    {% else %}
        <h2>
            Тест {{ testing.title }}
        </h2>
    {% endif %}
</section>
<section class='content__task-form task-form uk-margin' id='task-form'></section>
{% if quantity_task %}
    <h3 class='task-form__count-tasks'>
        Количество задач: {{ quantity_task }}
    </h3>
{% endif %}

src/templates/inc/_timer.html
<div class="uk-grid-small uk-child-width-auto uk-margin" id="timer" uk-grid
     uk-countdown="date: {{ end_passage }}" data-end-passage="{{ end_passage }}">
    <input type="hidden" id="duration" value="{{ duration }}">
    <div>Оставшееся время выполнения тестирования</div>
    <div>
        <div class="uk-countdown-number uk-countdown-hours"></div>
    </div>
    <div class="uk-countdown-separator">:</div>
    <div>
        <div class="uk-countdown-number uk-countdown-minutes"></div>
    </div>
    <div class="uk-countdown-separator">:</div>
    <div>
        <div class="uk-countdown-number uk-countdown-seconds"></div>
    </div>
</div>